export default {
  login: "shira1008",
  id: 109962964,
  node_id: "U_kgDOBo3m1A",
  avatar_url: "https://avatars.githubusercontent.com/u/109962964?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/shira1008",
  html_url: "https://github.com/shira1008",
  followers_url: "https://api.github.com/users/shira1008/followers",
  following_url:
    "https://api.github.com/users/shira1008/following{/other_user}",
  gists_url: "https://api.github.com/users/shira1008/gists{/gist_id}",
  starred_url: "https://api.github.com/users/shira1008/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/shira1008/subscriptions",
  organizations_url: "https://api.github.com/users/shira1008/orgs",
  repos_url: "https://api.github.com/users/shira1008/repos",
  events_url: "https://api.github.com/users/shira1008/events{/privacy}",
  received_events_url: "https://api.github.com/users/shira1008/received_events",
  type: "User",
  site_admin: false,
  name: "Shira Shahar",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 20,
  public_gists: 0,
  followers: 3,
  following: 3,
  created_at: "2022-07-25T12:01:50Z",
  updated_at: "2022-09-11T14:02:31Z",
};
